// <auto-generated />
namespace Lab2Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addsseed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addsseed));
        
        string IMigrationMetadata.Id
        {
            get { return "201712041354002_Adds seed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
