// <auto-generated />
namespace Lab2Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addsscores : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addsscores));
        
        string IMigrationMetadata.Id
        {
            get { return "201712041214064_Adds scores"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
